---
detectors:
  TooManyInstanceVariables:
    max_instance_variables: 6

directories:
  "app/application/forms": # form validations are funtional-oriented
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
  "app/application/services": # service scripts are funtional-oriented
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName: # for rescued errors
      enabled: false
    TooManyStatements: # for Success/Failure and rescued statements
      max_statements: 8
