---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - '_snippets/*'

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - Rakefile
    - app/application/controllers/**/*.rb # Roda's nested controllers require large blocks
    - spec/**/* # Minitest's nested test structure requires large blocks