---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  REED_TOKEN: This_Is_A_Sample_Reed_Token
  FREECURRENCY_API_KEY: This_Is_A_Sample_FreeCurrency_API_KEY
  SESSION_SECRET: asdfqwerzxcv

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  REED_TOKEN: This_Is_A_Sample_Reed_Token
  FREECURRENCY_API_KEY: This_Is_A_Sample_FreeCurrency_API_KEY
  SESSION_SECRET: asdfqwerzxcv
