---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  REED_TOKEN: This_Is_A_Sample_Reed_Token

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  REED_TOKEN: This_Is_A_Sample_Reed_Token
