---
development:
  SESSION_SECRET: asdfqwerzxcv
  APP_HOST: http://127.0.0.1:4000
  API_HOST: http://127.0.0.1:4001

test:
  SESSION_SECRET: asdfqwerzxcv
  APP_HOST: http://127.0.0.1:4000
  API_HOST: http://127.0.0.1:4001
